### ISSUE TITLE
Ax events dump doc example doesn't work on Windows

### ISSUE THREAD

**Issue by ostollmann** [Actyx/Actyx#324]
![image](https://user-images.githubusercontent.com/282765/155351816-49510154-216d-4172-a3e9-f595d865bb3a.png)

https://developer.actyx.com/docs/reference/cli/events/dump

**Comment by jmg-duarte** [comment]
Closing this issue as from testing, this is no longer happening.

Tested on
- `Actyx CLI 3.2.0`
- `Actyx CLI 3.1.0`
