### ISSUE TITLE
`ActyxClient::new` is too verbose

### ISSUE THREAD

**Issue by jmg-duarte** [Actyx/Actyx#552]
Example:
```rust
let client = ActyxClient::new(
        "http://localhost:4454".parse().unwrap(),
        AppManifest::new(
            app_id!("com.example.chat"),
            "simple chat".to_owned(),
            "0.1.0".to_owned(),
            None,
        ),
    )
    .await?;
```

A possible solution would be to offer something like:
```rust
// "http://localhost:4454" is assumed as a default connection location
let client = ActyxClient::local(
    AppManifest::new(...)
).await?;
```

However, this approach doesn't scale with future options, so another possibility could be 
```rust
let client = ActyxClient::new(ActyxClientOptions {
    manifest: AppManifest::new(),
    Default::default..
}).await?;
```

Furthermore, we can reduce it further by providing a `Default` implementation for `AppManifest` that returns a trial manifest (if the user wants to rename the manifest they can do so by using the "normal path").
For reference, said manifest would be something like:
```rust
AppManifest {
  app_id: app_id!("com.example.trial"),
  "trial_app",
  "0.0.1",
  None
}
```

Finally, we can also reduce verbosity on `AppManifest` by taking `&str` instead of `String` and cloning inside the method instead.

**Comment by rkuhn** [comment]
I like the idea of a default manifest! The analysis of the available Rust syntax features suggests that your proposal is indeed minimal, the only reduction potential lies in the length of the identifiers.

```rust
// trial manifest, default port
let ax = AxClient::new(AxOpts::default()).await?;

// trial manifest, other host:port
let ax = AxClient::new(AxOpts { url: "http://actyx:1234".parse()?, Default::default() }).await?;
// … or …
let ax = AxClient::new(AxOpts::url("http://actyx:1234"))?).await?;
```

**Comment by jmg-duarte** [comment]
I like this one, though I'd name it `with_url`/`with_address` instead because otherwise it feels like we're creating a special kind of URL for `AxOpts` only.
```rust
let ax = AxClient::new(AxOpts::url("http://actyx:1234"))?).await?;
```
