### ISSUE TITLE
publishing of `ax` to the website

### ISSUE THREAD

**Issue by rkuhn** [Actyx/Actyx#602]
We don’t publish Rust libraries (`ax-core` and friends) via `release` at this time. We manually `cargo publish` the libraries until we see enough need to automate this process.

The `release` tool needs a new product category for publishing the `ax` binary under the `ax` name (i.e. path prefix). This implies uploading `target/release/ax` to Azure blob store in CI.

`ax` versioning continues the Actyx series.

**Comment by Kelerchian** [comment]
The release tool part is related to https://github.com/Actyx/Actyx/issues/580

**Comment by rkuhn** [comment]
done
