### ISSUE TITLE
missing CMake and protobuf-compiler dependencies

### ISSUE THREAD

**Issue by asmodehn** [Actyx/Actyx#675]
Trying to run `cargo run --bin ax` just after a clone, on a new machine, I encountered two missing dependencies:
- cmake
- protobuf-compiler
I eventually figured it out, but I thought it would be useful to report here.

Not sure what would be the best way to make sure things compile without fail after cloning... but at least a line in the readme could be useful ?

**Comment by rkuhn** [comment]
Yes, good that you raise this — we installed these things a long time ago and forgot about it. Perhaps a section in the README could be accompanied by a tiny shell script that checks whether the commands are there?
